language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run export
- touch out/.nojekyll
deploy:
  provider: pages:git
  token: "$github_token"
  edge: true
  cleanup: false
  local_dir: out
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|main)$"
env:
  global:
    secure: WTvolWECmXmX4c/H6PwEIaFug9fhMw9Ky1z02QdRZTM63uu/OXdBYpBUvnUZiOt/c0zu192Ily+zEXcMHq4pY+0e0z5pTqL0EpzMQaSAEXzVRJCJKovHtuQPgu1cUOaHfhwa8CNLNrGm2W+ulLxXOC8F3WLQqNcmkSmtSpJO8/9eycmDIeFK4eXGQCCvc3+TZlV/XPNz/9ai9lG8tvBOgoUXC4/7D08Yr9LlTJSPW9CDuUhkbiU5z18lv7HaHmlarhhTd8bNyW5DyJ5KEPoyrQgoF0Zt1UhqLmC1MyKJs/+PufRZaAdFi75MLKqTw0KycK5RNaSEsVGzLz3xPZ8yheNtUeyWhYB7y4kYIvl9IJ4ggS5Ajfasq2o4XUlg4xagWoOJ/mOcOc1UEMAem7B1CHMcuIKHI/5Bfc5pDVjg8pjdlTNMjrB9eVc5rQiAPlrRVSz7ahAbbHHLG9B7dLiaDZYZFGI0QqrmVw1lM2UvjXRDrdkkx8HNTwwn+/Lrh3bYItocqJDaFETYiRpimB7NS5u1yrCYYX2PENQN/aHZYOSdfceAzItyGPi6F9BxpuFtx+NtOmWJMQ3dSKnsFrPm/5nfngB1dvOVdvBU1I/wOSjOYrhdQblaM3nnsFd9QwfP9WGg8XeIVRBSsUPtTqYXbww563AZS7/UfTbHr9tTzow=
